# Generated by Django 4.0.4 on 2022-05-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lecture_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='upload_to'),
        ),
    ]
